livecoders/website

package-lock.json
package.json
src/hooks/useLiveCoderStats.js
src/pages/index.js

Closes #6 
With usage of a few react hooks, I am pulling data from the live coders heatmap site and loading it into this site.

Adding clientside code to update weekly stats on frontpage

---

src/pages/about.js
src/pages/index.js
src/pages/members.js
src/templates/memberPage.js

This PR includes body copy for various portions of the site. If anyone has suggestions, please comment and review below.

Body copy for pages

---

src/members/fullstacklive.md

Here's the content for my stream page.

Initial content for FullStackLive

---

src/members/lilyhazel.md

updated LilyHazel.md

---

src/components/footer.js
src/css/memberPage.css
src/templates/memberPage.js

Closes #28. Added target="_blank" and rel="noopener noreferrer" to social links on members page.
Also make social links in mobile layout on a new row

update memberPage template

---

src/members/chaelcodes.md

Adding ChaelCodes' profile info to the Live Coders website! ✨

Add ChaelCodes profile info

---

src/css/index.css
src/css/memberPage.css
src/css/members.css
src/img/innerglow-top.svg
src/img/innerglow.svg
src/pages/members.js
src/templates/memberPage.js

Updated styling:
- General header and body font weights
- Added Google font weights for Roboto
- Updated styling on member cards on Team Members Page
- Updated styling on member page to style meta information

General member style changes

---

src/members/codephobia.md

Updated codephobia profile

---

src/members/jeffblankenburg.md

Thanks for making this so easy to update!

Added content to Jeff Blankenburg's page.

---

src/members/beachcasts.md

Added additional meta data for Beachcasts.

Updated Beachcasts info

---

src/members/jfversluis.md

Update jfversluis' profile

---

src/members/codingbandit.md

codingbandit - updated profile.

---

src/members/fboucheros.md

Adding description and bio on my page :)

Updating FBoucheros page

---

src/members/calvinaallen.md

Updating profile page for CalvinAAllen

---

src/members/thegrumpygamedev.md

i had a lot more to say about Mr. T, but I chopped it out.
i will share the haiku here:
T enters the room
Suckas and fools are pitied
Jibbajabba stops

i updatered TheGrumpyGameDev profile

---

src/members/davidwengier.md

I typed words about myself. It was hard.

Add member info for davidwengier

---

src/members/bryanlrobinson.md

Updates bio and links for bryanlrobinson member page

Bryanrobinson memberpage update

---

src/members/ramblinggeek.md

Updating Profile

---

src/pages/index.js

Updated Mission statement with the new one mission statement.

Updated Mission Statement

---

package-lock.json
package.json
src/pages/index.js

(Hello, it's me... it's you....)
- Does what it says on the tin
1. Added a 'start' command to the package
2. Added styled-components because that one familiar way to write CSS
3. Added a clickable piece of text to a banner on the home page for the LCC2 conference.

Add conference promotion

---

src/members/jitterted.md

Fill out Jitterted.md

---

src/members/cldubya.md

Adds social info, tags, schedule, and a brief description of my stream

Updates cldubya.md

---

src/members/devchatter.md

Finally getting around to adding at least *something* to the DevChatter info on the site.

Update devchatter.md Links and Info

---

src/members/bdougieyo.md

I updated my bio and links. Thanks

Update bdougieyo.md links and description

---

src/members/fullstacklive.md

Update member page FullStackLive

---

src/members/jenninexus.md

Trying to make it look nicer :-)

---

src/members/phil_nash.md

Adds details for my page.

---

src/members/tbdgamer.md

Updated with more up to date skills and updated profile content.

Updated profile

---

package-lock.json
scripts/genOGImages/package.json

Applied all security patches recommended by npm

npm security patch

---

scripts/genMembers/index.js
scripts/genMembers/package-lock.json
scripts/genMembers/package.json

If no users are identified to add or remove:
- Logs that no action is being taken
If members are identified that have not appropriately been added:
- Logs that the user is being added to the repo
- Adds the user to the repo as it has previously done
If members are identified in the repo that are no longer on the team:
- Logs that the user is being removed from the repo
- Removes the `/src/members/{twitchHandle}.md` file from the repo
- Removes the `/src/img/members/{twitchHandle}.*` file from the repo

Update genMembers to improve logging and process member removal 

---

src/components/conference/sponsors.js
src/components/event-banner.js
src/components/header.js
src/pages/iwd-2021.js

This adds a placeholder for the International Womens' Day event page, as well as a site-wide banner for it (currently disabled). Screenshots below:

Create placeholder conf page

---

src/members/ml_astra.md

Updated my personal member page with some info and the tags for the Live Coders site.

Updated ML-Astra Member page

---

.github/workflows/build.yml
.github/workflows/gen-members.yml

This should also reduce the likelihood for breakage in the future since now we should be able to see for every PR whether the site can still be built.

Updated/Fixed CI and build on every push/PR

---

.github/workflows/gen-members.yml

Install dependencies from package.json to deloy site

---

.github/workflows/build.yml

Install packages for build workflow as well
Details: #300

Install dependencies from package.json on site build
